
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 01 10:19:55 CST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 18;
  public static final int FROM = 17;
  public static final int AND = 14;
  public static final int GROUPBY = 19;
  public static final int SELECT = 16;
  public static final int OR = 15;
  public static final int EQUAL = 12;
  public static final int SEMI = 4;
  public static final int NOTEQUAL = 13;
  public static final int LTOE = 10;
  public static final int STAR = 6;
  public static final int ID = 2;
  public static final int GTOE = 11;
  public static final int COMMA = 3;
  public static final int LESSTHAN = 8;
  public static final int EOF = 0;
  public static final int STRINGLIT = 20;
  public static final int DISTINCT = 7;
  public static final int error = 1;
  public static final int DOT = 5;
  public static final int GREATERTHAN = 9;
}

